### PR TITLE
Sanic ctx upgrade: Update the request namespace to newer sanic ctx

### PR DESCRIPTION
**Pull request by Arvind2222**
Changed the sanic request ctx for __START_TIME__ for the middleware is going to be deprecated, added the newer ctx way for adding custom objects.

### CODE REVIEW

**Comment by Arvind2222** [comment]
@dkruchinin Please take a look and do the needful.

**Comment by Arvind2222** [comment]
@SirEdvin @skar404 Hi, please check if I am missing anything.

**Comment by joekohlsdorf** [comment]
can we get this merged?

**Review by dkruchinin — APPROVED** [review]
Hi @Arvind2222
Sorry for late response and thank you so much for your PR. Approved and merged 🙏

**Comment by reb00ter** [comment]
@dkruchinin will you update package version with this fix on pypi?

**Comment by ajcolaizzi-decentrix** [comment]
@dkruchinin @Arvind2222 can we expect a realise anytime soon?

**Comment by joekohlsdorf** [comment]
> @dkruchinin @Arvind2222 can we expect a release anytime soon?

I recommend you to just use the prometheus-sanic fork which actually works: https://github.com/skar404/prometheus-sanic

**Comment by dkruchinin** [comment]
Hi @reb00ter, @joekohlsdorf, @Arvind2222 

Just released a new version. I haven't been paying much attention to the project recently and I can not promise I'll keep an eye on it in near future. So, I'm happy to give the rights to the repo to anyone who's interested in keeping the project alive and more up-to-date. Let me know if I shall give the rights to any of you.

Thank you and apologies for the delay.

**Comment by ajcolaizzi-decentrix** [comment]
@dkruchinin Thank you for releasing that and giving us an update. 

I don't have the bandwidth to do so right now. If we need to upgrade past the current version, we can look for other projects/options.

Cheers.

**Comment by Arvind2222** [comment]
> Hi @reb00ter, @joekohlsdorf, @Arvind2222
> 
> Just released a new version. I haven't been paying much attention to the project recently and I can not promise I'll keep an eye on it in near future. So, I'm happy to give the rights to the repo to anyone who's interested in keeping the project alive and more up-to-date. Let me know if I shall give the rights to any of you.
> 
> Thank you and apologies for the delay.

@dkruchinin  I would be more than happy for the access.

Also thanks for the release. Github stopped emailing updates on the thread so did not check.

**Pull request merged**
